---
abstract: 'counts of CPAN Testers reports by month or year'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  Test::More: 0.88
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Testers-Reports-Counts
requires:
  Exporter: 0
  Net::HTTP::Tiny: 0
  parent: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/neilbowers/CPAN-Testers-Reports-Counts
  repository: https://github.com/neilbowers/CPAN-Testers-Reports-Counts.git
version: 0.04
